### ISSUE TITLE
Improve tile looks of event page

### ISSUE THREAD

**Issue by Bhola-B2C** [lugnitdgp/avskr2.0#7]
Make it as poster background or a gaming related

**Comment by SingularReza** [comment]
Shreyashee di said we are going to use icon like images for it. I will do it once they were prepared

**Comment by Bhola-B2C** [comment]
Okay

**Comment by Bhola-B2C** [comment]
@SingularReza You can ask for the event tiles to designer team. No need to wait for that. Complete this issue asap.
